# Generated by Django 3.2.25 on 2025-11-24 16:21

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20251120_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=demo.models._default_expiry),
        ),
    ]
