# Generated by Django 3.2.25 on 2026-02-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_apikey_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedText',
        ),
    ]
