services:
  medcatweb:
    build:
      context: ./webapp
    volumes:
      - ../medcat-v2/tests/resources:/webapp/models
    ports:
      - "8000:8000"
    env_file:
      - ./envs/env_medmen_test
    tty: true
