# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   commit-message:
     prefix: "build: "
   schedule:
     interval: weekly
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build: "
   groups:
     actions-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/anoncat-demo-app"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(anoncat-demo-app): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/anoncat-demo-app/app"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(anoncat-demo-app): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "npm"
   directory: "/anoncat-demo-app/app/frontend"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(anoncat-demo-app): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     npm-deps:
       applies-to: version-updates
       patterns:
        - "*"
     npm-security-deps:
       applies-to: security-updates
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/cogstack-es"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(cogstack-es): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-den"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-den): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-model-distributor/webapp"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-model-distributor): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-plugins/embedding-linker"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-plugins): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-plugins/medcat-gliner"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-plugins): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-scripts"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-scripts): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-service"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-service): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "pip"
   directory: "/medcat-trainer/client"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-trainer): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     pip-deps:
       patterns:
        - "*"
 - package-ecosystem: "uv"
   directory: "/medcat-trainer/webapp"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-trainer): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     uv-deps:
       applies-to: version-updates
       patterns:
        - "*"
     uv-security-deps:
       applies-to: security-updates
       patterns:
        - "*"
 - package-ecosystem: "npm"
   directory: "/medcat-trainer/webapp/frontend"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-trainer): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     npm-deps:
       applies-to: version-updates
       patterns:
        - "*"
     npm-security-deps:
       applies-to: security-updates
       patterns:
        - "*"
 - package-ecosystem: "uv"
   directory: "/medcat-v2"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     uv-deps:
       applies-to: version-updates
       patterns:
        - "*"
     uv-security-deps:
       applies-to: security-updates
       patterns:
        - "*"
 - package-ecosystem: "uv"
   directory: "/medcat-v2-tutorials"
   schedule:
     interval: "weekly"
   commit-message:
     prefix: "build(medcat-tutorials): "
   allow:
     - dependency-name: "*"
       update-types:
         - "version-update:semver-patch"
         - "version-update:semver-minor"
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major"]
   groups:
     uv-deps:
       applies-to: version-updates
       patterns:
        - "*"
     uv-security-deps:
       applies-to: security-updates
       patterns:
        - "*"
