# Generated by Django 3.2.25 on 2025-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_downloader_medcatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='downloader',
            name='downloaded_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medcatmodel',
            name='model_description',
            field=models.TextField(max_length=200),
        ),
    ]
