# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: MedCAT Tutorials
site_url: https://docs.cogstack.org/

theme:
  name: material
  favicon: _static/img/cat-logo.svg
  logo: _static/img/cat-logo.svg
  icon:
    logo:  _static/img/cat-logo.svg
  palette:
    primary: white

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - header.autohide
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - attr_list

repo_url: https://github.com/CogStack/cogstack-nlp
repo_name: cogstack-nlp

docs_dir: notebooks

nav:
  - Home: index.md
  - Introductory Tutorials:
    - Basic:
      - README: introductory/basic/README.md
      - 1. Build a Concept Database and a Vocabulary: introductory/basic/1._Build_a_Concept_Database_and_a_Vocabulary.ipynb
      - 2. Unsupervised training on model: introductory/basic/2._Unsupervised_training_on_model.ipynb
      - 3. Supervised training on model: introductory/basic/3._Supervised_training_on_model.ipynb
      - 4. Evaluating performance on dataset: introductory/basic/4._Evaluating_performance_on_dataset.ipynb
    - MetaCAT:
      - README: introductory/meta/README.md
      - 1. Add a MetaCat to a Model: introductory/meta/1._Add_a_MetaCat_to_a_Model.ipynb
    - RelCAT:
      - 1. Supervised Training Relation Extraction: introductory/relcat/1._Supervised_Training_Relation_Extraction.ipynb
      - 2. Infering relations from annotations with Relation toolkit: introductory/relcat/2._Infering_relations_from_annotations_with_Relation_toolkit.ipynb

  - Advanced Tutorials:
    - 1. Creating and using a custom tokenizer: advanced/1._Creating_and_using_a_custom_tokenizer.ipynb
    - 2. Create and use component: advanced/2._Create_and_use_component.ipynb
    - Custom Components:
      - README: introductory/custom/README.md
      - 1. Create Modelpack with 2step linker: introductory/custom/1._Create_Modelpack_with_2step_linker.ipynb
    - Migration:
      - README: introductory/migration/README.md
      - 1. Migrate v1 model to v2: introductory/migration/1._Migrate_v1_model_to_v2.ipynb

plugins:
  - search
  - termynal
  - autorefs  # Resolves cross-refs from mkdocstrings so type links work across pages
  - mkdocs-jupyter:
      ignore_h1_titles: True

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
