"""
Django settings for MedCATtrainer project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import logging
import os
import sys

log = logging.getLogger(__name__)

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

environ_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
trusted_origins = [origin.strip() for origin in environ_origins.split(',') if origin.strip()]

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8001', 'http://localhost:8001'] + trusted_origins

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# SECURITY WARNING: keep the secret key used in production secret!
realm = os.environ.get('ENV', 'non-prod')
secret_key = os.environ.get('SECRET_KEY')
if realm == 'prod' and secret_key is None:
    msg = 'No SECRET_KEY environment variable found for prod environment. Please add a secret key and re-run'
    log.error(msg)
    sys.exit(msg)
else:
    log.info('Running non-prod environment, defaulting django SECRET_KEY')
    SECRET_KEY = 'q$&esydgbn2=#-k5s5i(+^dtxs1@$50_(ln0wuw@zig4m&^m7='

# SECURITY WARNING: don't run with debug turned on in production!
try:
    DEBUG = bool(int(os.environ.get('DEBUG', 1)))
    if realm == 'prod' and DEBUG:
        log.warning('Running in prod realm with DEBUG=True, are you sure you want to do that?')
except ValueError as e:
    log.error('Error parsing DEBUG env, setting DEBUG to True. DEBUG env var should be set to 0 (false) or 1 (true).')
    DEBUG = True

ALLOWED_HOSTS = ['*']

APPEND_SLASH = True

USE_OIDC = os.getenv('USE_OIDC', '').lower() == '1'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'background_task',
    'api',
    'health_check',
    'health_check.contrib.db_heartbeat',
    'health_check.contrib.migrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "..", "frontend", "dist"),
            os.path.join(BASE_DIR, "..", "templates", "registration")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {module}.py l:{lineno}:{message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    }
}


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

db_engine = os.environ.get("DB_ENGINE", "sqlite3").lower()
if db_engine not in ("sqlite3", "postgresql"):
    raise ValueError("DB_ENGINE must be 'sqlite3' or 'postgresql'")

if db_engine == "postgresql":
    DB_NAME = os.environ.get("DB_NAME", "postgres")
    DB_USER = os.environ.get("DB_USER", "")
    DB_PASSWORD = os.environ.get("DB_PASSWORD", "")
    DB_HOST = os.environ.get("DB_HOST", "")
    DB_PORT = os.environ.get("DB_PORT", "5432")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db/db.sqlite3'),
            'OPTIONS': {
                'timeout': 20,
                'transaction_mode': 'IMMEDIATE'
            }
        }
    }

# https://pypi.org/project/django-health-check/
HEALTH_CHECK = {
    "SUBSETS": {
        'startup': ['DatabaseHeartBeatCheck', 'MigrationsHealthCheck'],
        'live': [],
        'ready': ['DatabaseHeartBeatCheck'],
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication'
    ]
}

if USE_OIDC:
    log.info("Using OIDC authentication")
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
        'oidc_auth.authentication.JSONWebTokenAuthentication',
        'oidc_auth.authentication.BearerTokenAuthentication',
    ]

    OIDC_HOST = os.environ.get('OIDC_HOST', '')
    OIDC_REALM = os.environ.get('OIDC_REALM', default='cogstack-realm')
    OIDC_BACKEND_CLIENT_ID = os.environ.get('OIDC_BACKEND_CLIENT_ID', default='cogstack-medcattrainer-backend')
    OIDC_BACKEND_CLIENT_SECRET = os.environ.get('OIDC_BACKEND_CLIENT_SECRET', default='')
    OIDC_FRONTEND_CLIENT_ID = os.environ.get('OIDC_FRONTEND_CLIENT_ID', default='cogstack-medcattrainer-frontend')
    OIDC_AUTH = {
        'OIDC_ENDPOINT': f"{OIDC_HOST}/realms/{OIDC_REALM}",
        'OIDC_CLAIMS_OPTIONS': {
            'aud': {
                'values': [
                    'account',
                    OIDC_BACKEND_CLIENT_ID,
                    OIDC_FRONTEND_CLIENT_ID
                ],
                'essential': True,
            },
            'iss': {
                'values': [
                    f"{OIDC_HOST}/realms/{OIDC_REALM}"
                ],
                'essential': True,
            },
        },
        'USERINFO_ENDPOINT': f"{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo",
        'OIDC_CREATE_USER': True,
        'OIDC_RESOLVE_USER_FUNCTION': 'api.oidc_utils.get_user_by_email',
        'OIDC_CLIENT_ID': OIDC_BACKEND_CLIENT_ID,
        'OIDC_CLIENT_SECRET': OIDC_BACKEND_CLIENT_SECRET,
    }


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MEDIA_URL = '/media/'
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

FILE_UPLOAD_PERMISSIONS = 0o644

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "..", "frontend", "dist", "static"),
]

# BG TASKS
MAX_ATTEMPTS = 1
MAX_RUN_TIME = 60*60*10
BACKGROUND_TASK_RUN_ASYNC = True
BACKGROUND_TASK_ASYNC_THREADS = 4


# Solr Concept Search settings
SOLR_HOST = os.environ.get('CONCEPT_SEARCH_SERVICE_HOST', 'solr')
SOLR_PORT = os.environ.get('CONCEPT_SEARCH_SERVICE_PORT', '8983')

SILENCED_SYSTEM_CHECKS = ['admin.E130']

# For testing only
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
EMAIL_USE_TLS = True
