# Generated by Django 5.1.11 on 2025-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_exportedproject_cdb_search_filter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannotateentities',
            name='model_service_url',
            field=models.CharField(blank=True, help_text='URL of the remote MedCAT service API (e.g., http://medcat-service:8000)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectannotateentities',
            name='use_model_service',
            field=models.BooleanField(default=False, help_text='Use a remote MedCAT service API for document processing instead of local models'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='model_service_url',
            field=models.CharField(blank=True, help_text='URL of the remote MedCAT service API (e.g., http://medcat-service:8000)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='use_model_service',
            field=models.BooleanField(default=False, help_text='Use a remote MedCAT service API for document processing instead of local models'),
        ),
    ]
