# Generated by Django 5.2.11 on 2026-02-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_add_remote_model_service_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectannotateentities',
            options={},
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='use_model_service',
            field=models.BooleanField(default=False, help_text='Use a remote MedCAT service API for document processing instead of local models(note: interim model training is not supported for remote model service projects)'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='use_model_service',
            field=models.BooleanField(default=False, help_text='Use a remote MedCAT service API for document processing instead of local models(note: interim model training is not supported for remote model service projects)'),
        ),
    ]
