name: medcat-demo-app - Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'medcat-demo-app/**'
      - 'medcat-v2/**'
      - '.github/workflows/medcat-demo-app**'
defaults:
  run:
    working-directory: ./medcat-demo-app

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      MEDCAT_BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v5

    - name: 🧹 Free up disk space
      run: |
        df -h # Optional: Check space before build
        # Remove large, unnecessary packages/tools
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/rust
        sudo rm -rf /usr/share/powershell
        # Remove cached tools and files
        sudo apt-get clean
        df -h # Optional: Check space before build

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Make medact-v2 available within webapp
      run: cp -r ../medcat-v2 webapp/medcat-v2

    - name: Build and start containers
      run: docker-compose -f docker-compose-test.yml up -d --build

    - name: Run integration test
      run: ./tests/test_integration.sh

    - name: Check container logs for errors
      run: |
        docker-compose logs medcatweb
        # NOTE: ignore line "Applying auth.0007_alter_validators_add_error_messages" - not an error
        docker-compose logs medcatweb | grep -v "Applying auth.0007_alter_validators_add_error_messages" | grep -i 'error' && exit 1 || true

    - name: Tear down
      run: docker-compose -f docker-compose-test.yml down
