# .github/workflows/upload-test-models.yml
name: Upload test models to release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  upload-test-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Upload test models to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.tag }} medcat-test-models/* --clobber

